#!/usr/bin/env bash
# generate-inventory.sh — emit an Ansible YAML inventory from the 50-compute
# layer's `ansible_inventory` OpenTofu output, written to stdout.
#
#   AWS_PROFILE=brzl-apply bash generate-inventory.sh > inventory/dev.yml
#
# OpenTofu state is the single source of truth for which nodes exist and how to
# reach them; this turns that into an Ansible inventory. Printing to stdout (per
# the repo bash convention) keeps the result auditable before you save it.
#
# No `set -euo pipefail` (see CLAUDE.md / BashPitfalls/105): the only command
# whose failure matters is the `tofu output`, which we check explicitly; an empty
# result (infra is down) is a real, reportable outcome, not a crash.

if (( BASH_VERSINFO[0] < 4 )); then
  printf 'error: bash >= 4 required\n' >&2
  exit 1
fi

# Default to the dev compute layer relative to this script's location, so it
# works regardless of the caller's CWD; override by passing a path as $1.
script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
layer_dir="${1:-${script_dir}/../../terraform/environments/dev/50-compute}"

if ! command -v tofu >/dev/null 2>&1; then
  printf 'error: tofu not found on PATH\n' >&2
  exit 1
fi

if ! inv_json="$(tofu -chdir="$layer_dir" output -json ansible_inventory 2>/dev/null)"; then
  inv_json=""
fi
if [[ -z "$inv_json" || "$inv_json" == "null" || "$inv_json" == "[]" ]]; then
  printf 'error: no ansible_inventory output from %s\n' "$layer_dir" >&2
  printf '       is 50-compute applied, and are AWS creds set (AWS_PROFILE=brzl-apply)?\n' >&2
  exit 1
fi

# shellcheck disable=SC2016  # the python program is intentionally literal (no shell expansion wanted)
printf '%s' "$inv_json" | python3 -c '
import json, re, sys
nodes = json.load(sys.stdin)
# The env key pair name is the node-name prefix (brzl-<env>-node-1 -> brzl-<env>-node),
# matching the key the env 50-compute layer writes to ~/.ssh (secrets.tf).
key_name = re.sub(r"-\d+$", "", nodes[0]["name"])
out = []
out.append("# GENERATED by ansible/inventory/generate-inventory.sh - do not edit by hand.")
out.append("# Source of truth: the 50-compute `ansible_inventory` OpenTofu output.")
out.append("# ansible_host is the EC2 instance-id: Ansible reaches each node through")
out.append("# SSM (the SSH-over-SSM ProxyCommand in ansible.cfg), not by IP.")
out.append("k3s_servers:")
out.append("  vars:")
out.append("    # Per-env TF-generated key (overrides the ansible.cfg dev default).")
out.append("    ansible_ssh_private_key_file: ~/.ssh/%s" % key_name)
out.append("  hosts:")
for i, n in enumerate(nodes):
    out.append("    %s:" % n["name"])
    # SSM target the ProxyCommand connects to (NOT an IP).
    out.append("      ansible_host: %s" % n["instance_id"])
    out.append("      instance_id: %s" % n["instance_id"])
    out.append("      private_ip: %s" % n["private_ip"])
    # Public IP is informational only (kubectl/API reachability); SSH no longer
    # uses it. Emitted only when the node actually has one (dev).
    if n.get("public_ip"):
        out.append("      public_ip: %s" % n["public_ip"])
    out.append("      node_az: %s" % n["az"])
    # First node bootstraps the HA control plane (k3s --cluster-init); the rest
    # join it. Lets the kubernetes role branch without hardcoding a hostname.
    out.append("      k3s_primary: %s" % ("true" if i == 0 else "false"))
print("\n".join(out))
'
